### ISSUE TITLE
Set fsType to 0

### ISSUE THREAD

**Issue by davelab6** [Omnibus-Type/Jaldi#11]
- [x] fsType should be 0

```
$ fontbakery-fix-fstype.py *ttf
ER: Jaldi-Bold.ttf 8: Change to 0
ER: Jaldi-Regular.ttf 8: Change to 0
```

**Comment by Omnibus-Type** [comment]
Please,  check again this, in OTMaster seems to appear fine.
![screen shot 2015-04-13 at 3 37 55 pm](https://cloud.githubusercontent.com/assets/8041808/7126989/1f1b4ef2-e1f3-11e4-80a7-36b0c34d00d3.png)

**Comment by zar-nicolas20** [comment]
That was fixed,
Once @davelab6 confirm that Jaldi is working as expected I will close this issue.

**Comment by davelab6** [comment]
> Once @davelab6 confirm that Jaldi is working as expected

Was the update shipped in the API?

**Comment by zar-nicolas20** [comment]
I don't know.

**Comment by davelab6** [comment]
I confirm it was.
