### ISSUE TITLE
Vertical metrics to bounding box

### ISSUE THREAD

**Issue by davelab6** [Omnibus-Type/Jaldi#12]
- [ ] Vertical metrics should be changed to 2350/-1111/0 

```
$ fontbakery-fix-vertical-metrics.py *ttf
Parameter              Jaldi-Bold.ttf    Jaldi-Regular.ttf    
ymax                   2350              2350                 
hhea.ascent            2349              2349                 
OS/2.sTypoAscender     2349              2349                 
OS/2.usWinAscent       2349              2349                 
ymin                   -1111             -972                 
hhea.descent           -1094             -1094                
OS/2.sTypoDescender    -1094             -1094                
OS/2.usWinDescent      1094              1094                 
hhea.lineGap           0                 0                    
OS/2.sTypoLineGap      0                 0                    
hhea total             3443              3443                 
typo total             3443              3443                 
win total              3443              3443                 
UPM:Heights            2048:3461         2048:3322            
UPM:Heights %          168 %             162 %                

High Glyphs
Jaldi-Bold.ttf: uni1CDA uni1CDB uni0951
Jaldi-Regular.ttf: uni1CDA uni1CDB uni0951

Low Glyphs
Jaldi-Bold.ttf: uni093C094D09300962 uni093C094D09300944 uni093C094D09300943

$
```

**Comment by Omnibus-Type** [comment]
I can't understand from where the `-1111` vaule is. This is the result of my test
Jaldi (master: Bold)

```
Lowest selected glyphs:
- nukta_rakar_lVocalicMatra-deva: -1094.4
- nukta_rakar_rrVocalicMatra-deva: -1094.0
- nukta_rakar_rVocalicMatra-deva: -1093.8
- nukta_rakar_llVocalicMatra-deva: -1092.9
- nukta_rakar_uuMatra-deva: -1084.7
- nukta_rakar_uMatra-deva: -1084.4
- llVocalicMatra-deva: -782.5
- ng_k_ssa-deva: -781.5
- ng_gh_ra-deva: -770.0
- ng_g_ra-deva: -769.0
- tt_ttha-deva: -766.4
- tth_ttha-deva: -766.4
```

Nevertheless I will set -111 the descent

**Comment by Omnibus-Type** [comment]
Matched the ascender and descender values, please confirm this.
![screen shot 2015-04-13 at 3 40 44 pm](https://cloud.githubusercontent.com/assets/8041808/7127033/8fffb66c-e1f3-11e4-9cce-5d8edad29b97.png)

**Comment by davelab6** [comment]
> I can't understand from where the -1111 value is.

It seems to be in one of Jaldi-Bold.ttf's uni093C094D09300962, uni093C094D09300944 or uni093C094D09300943  according to `fontbakery-fix-vertical-metrics.py` - you could install https://github.com/googlefonts/fontbakery yourself to verify.

> please confirm this

From this screenshot it appears you are multiplying the 1.000 upm OTF by 2,048 to get a 2.048 upm TTF, but this is not neccessary and increases the filesize. Please don't do that :)

**Comment by Omnibus-Type** [comment]
Jaldi in OTF, EOT, WOFF and WOFF2 has non-integral values (a consequences of its rounded terminals), so I multiply the embox in order to generated the TTF file with integral values in its coordinates. It is the only exception. Please let me know if this is fine.

**Comment by Omnibus-Type** [comment]
It is a problem during the generation of the TTF (and how Glyphs take the anchors values of components). I will fix this promptly.
![screen shot 2015-04-13 at 5 23 13 pm](https://cloud.githubusercontent.com/assets/8041808/7128051/c8295882-e201-11e4-9c07-64223aaa4a07.png)

**Comment by Omnibus-Type** [comment]
Fixed

**Comment by davelab6** [comment]
Aha! Great we caught this :)

**Comment by davelab6** [comment]
BTW, `v.1.004-beta.2` doesn't make sense, because such a version can't exist in the HEAD and NAME tables; its best to just increment the x value in the 1.x each time, from 001 upwards, each time you generate new binaries.

**Comment by Omnibus-Type** [comment]
Ok, so as little modifications as minor changes are, I shall increment the last number. Fine, I will keep it in mind for the next releases. Do you want I updated the Pragati version record? (at least Jaldi is one number higher than the latest release.
BTW Thanks for pointing me the issues with Jaldi.

**Comment by davelab6** [comment]
Yes, even though they are little, since users can download the binaries and install them, having the version number clearly incremented is helpful for debugging and answering 'have you got the latest version installed?' :)

**Comment by Omnibus-Type** [comment]
I run the fonts without installing in the OS
http://www.glyphsapp.com/tutorials/testing-your-fonts-in-adobe-apps

**Comment by zar-nicolas20** [comment]
Fonts running in OS X. @davelab6 , Any feedback or open point in this issue?

**Comment by davelab6** [comment]
> Jaldi in OTF, EOT, WOFF and WOFF2 has non-integral values (a consequences of its rounded terminals), so I multiply the embox in order to generated the TTF file with integral values in its coordinates. It is the only exception. Please let me know if this is fine.

Yes, good

> Any feedback or open point in this issue?

is the update shipped in the Fonts API?

**Comment by zar-nicolas20** [comment]
What I need to do to to update Jaldi in the API?

**Comment by Omnibus-Type** [comment]
Closing this issue, it was addressed in the latest commit
