### ISSUE TITLE
GlyphData.xml?

### ISSUE THREAD

**Issue by davelab6** [Omnibus-Type/Jaldi#14]
This repo used to contain a GlyphData.xml - where did it go? :) 

I see https://github.com/Omnibus-Type/PragatiNarrow/blob/master/SRC/GlyphData.xml is still there

**Comment by Omnibus-Type** [comment]
GlyphData.xml added to Jaldi. It is better to have all resources repo independent.

**Comment by Omnibus-Type** [comment]
XML added to the repo. Closing Issue
